# Generated by Django 3.1.2 on 2020-11-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Verbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(max_length=200)),
                ('verb_type', models.CharField(max_length=200)),
                ('reguler', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
