# Generated by Django 3.1.2 on 2020-11-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbs',
            name='level',
            field=models.CharField(max_length=200),
        ),
    ]
