# Generated by Django 3.1.2 on 2020-11-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamo', '0002_auto_20201125_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbs',
            name='dfn',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='verbs',
            name='en_dfn',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='verbs',
            name='en_w',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='verbs',
            name='target_code',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
