# Generated by Django 3.1.2 on 2020-11-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamo', '0003_auto_20201130_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbs',
            name='dfn',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='verbs',
            name='en_w',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='verbs',
            name='target_code',
            field=models.TextField(default='', null=True),
        ),
    ]
