# Generated by Django 3.1.2 on 2020-11-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamo', '0004_auto_20201130_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbs',
            name='target_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
