# Generated by Django 3.1.2 on 2020-12-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamo', '0005_auto_20201130_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verbs',
            old_name='dfn',
            new_name='example',
        ),
        migrations.RemoveField(
            model_name='verbs',
            name='en_dfn',
        ),
    ]
