# Generated by Django 3.1.2 on 2020-12-15 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamo', '0007_myverbs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verbs',
            options={'ordering': ['pk']},
        ),
    ]
