# Generated by Django 3.1.2 on 2020-12-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamo', '0008_auto_20201215_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myverbs',
            name='verbList',
            field=models.ManyToManyField(related_name='verblist', to='jamo.Verbs'),
        ),
    ]
