# Generated by Django 3.1.2 on 2021-01-01 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamo', '0009_auto_20201215_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verbs',
            options={},
        ),
    ]
